
```{r render_Dygraph}
######################################## CREATE MAIN TIME SERIES DISPLAY
if(shiny_running()){
  output$dygraph<-
    renderDygraph({
      ################################## NEW FILES NEED NEW BOUNDARIES -> "retainDateWindow"
      if(ExG$newfile){
          d<-dygraph(ExG$disp) %>% 
            dyAxis("y", label = "Electric Potential (EEG-uV / E(CMO)G-mV)",valueRange=c(-50,50)) %>%
            dyRangeSelector(height = 90) %>%
            dyOptions(axisLineWidth = 1.5, drawGrid = FALSE,connectSeparatedPoints=T) %>%
            dyLegend(show = "never")
          ExG$newfile=F
      }else{
        d<-dygraph(ExG$disp) %>% 
          dyAxis("y", label = "Electric Potential (V)",valueRange=c(-50,50)) %>%
          ############################# RANGE SELECTION FOR ROLLING MEAN SIGNAL GRAB
          dyRangeSelector(height = 90,retainDateWindow=T) %>% dyLegend(show = "never") %>%
          dyOptions(axisLineWidth = 1.5, drawGrid = FALSE,connectSeparatedPoints=T) %>% 
          ############################# CLICK-HANDLING FOR STAGING
          dyCallbacks(
            annotationClickHandler=
          "function(ann, point, dg, event){
          ann.div.style.backgroundColor =  '#ddd';
          var message=ann.text;
          Shiny.onInputChange('downRater',0);
          Shiny.setInputValue('downRater',message);}")
      }
      
    if("Bandpower" %in% input$disp_event){
      # Take Bandpower columns - always last ones
      dn<-colnames(ExG$disp)[(ncol(ExG$disp)-4):(ncol(ExG$disp))]
        for(i in 1:length(dn)){
          #display them on other y axis
          d<-d %>% dySeries(dn[i], axis = 'y2',stepPlot = F,
                   color=c("#edf8fb","#b3cde3","#8c96c6","#8856a7","#810f7c")[i])%>%
            dyAxis("y2", label = "Bandpower (%)",valueRange=c(0,100))
        }
    }
      
    if("Stages" %in% input$disp_event){
      for(i in 1:(nrow(ExG$stages))){
        if(any(ExG$stages[i,1] %in% c("W","S1","S2","S3","REM","A") )){
          ## Get the closest index value of the displayed time series
          ## Write the annotation there - otherwise does not show an annotation bc timestamp might be missing
            d= d %>% dyAnnotation(index(ExG$disp)[
              which(abs(index(ExG$disp)-ExG$stages[i,2])==min(abs(index(ExG$disp)-ExG$stages[i,2])))],
              text=ExG$stages[i,1],tooltip = as.character(i),width=30,height=30)
          }
      }
    }
      
    if("Sleep Spindles" %in% input$disp_event){
      for(i in 1:(nrow(ExG$spindles))){
        ## same as above, closest existing timestamp, events are the Sleep Spindles only atm
        d= d %>% dyAnnotation(index(ExG$disp)[
          which(abs(index(ExG$disp)-ExG$spindles[i,2])==min(abs(index(ExG$disp)-ExG$spindles[i,2])))],
          text="Sp",attachAtBottom =T,width=20,height=20)
      }
    }
      if("QRS-Complex" %in% input$disp_event){
      for(i in 1:(nrow(ExG$qrs))){
        ## same as above, closest existing timestamp, events are the Sleep Spindles only atm
        d= d %>% dyAnnotation(index(ExG$disp)[
          which(abs(index(ExG$disp)-ExG$qrs[i,2])==min(abs(index(ExG$disp)-ExG$qrs[i,2])))],
          text="QRS",attachAtBottom =T,width=20,height=20)
      }
      }
      ###################DISPLAY d at render POSITION
    d
  })
}
```

```{r timeseries_ui}
### FIRST PANEL UI ELEMENTS PLACEMENT
if(shiny_running()){
  fillCol(
    fillRow(
      actionButton("upload","Upload new Data ... "),
        renderUI({
          chansels=colnames(ExG$ts)
          pickerInput(
          inputId = "disp_chan",
          choices =chansels,
          options = list(title = "Channels",
                         `actions-box` = TRUE,size = 8,`selected-text-format` = "count > 3"),
          multiple = TRUE
          )
        }),
        pickerInput(
          inputId = "disp_event",
          choices = c("Bandpower","Stages","Sleep Spindles","QRS-Complex"),
          options = list(title = "Events",
                         `actions-box` = TRUE,size = 8,`selected-text-format` = "count > 3"),
          multiple = TRUE
          ),
        renderUI({
          sel_choices=colnames(ExG$rssa)
          pickerInput(
            inputId = "disp_ssa",
            choices = sel_choices,
            options = list(title = "Clusters",
                           `actions-box` = TRUE,size = 8,`selected-text-format` = "count > 3"),
          multiple = TRUE
          )
        }),
      renderPrint(length(ExG$ts))
        # switchInput(inputId = "sep_chan",
        #             label = "parallel lines", value=F)
      ,flex=c(1,2,2,2,1)),
    ### INPUTS FINISHED -> NEXT COLUMN: GRPAHIC
    dygraphOutput("dygraph")
    ,flex = c(1,10))
}else{
  ## STATIC DISPLAY HYPNOGRAM
  # it's W, REM, S1, S2, S3,
  # d=data.frame(x=c(1,2,4,5,7,8,9), y=c(1,2,3,5,6,7,9))
  d=EXG$stages
  d[,1]=factor(d[,1],levels = c("S3","S2","S1","REM","W","A"))
  colnames(d)=c("y","x")
ggplot() +
geom_step(data=d, mapping=aes(x=x, y=y),group=1)+theme_classic()
}

if(shiny_running()){
observeEvent(input$upload,{
  ###################################### BY CLICK ON UPL BTN -> SHOW THIS
  showModal(modalDialog(
    #################################### POSSIBLY REDUCE OPTIONS FOR READABILITY
    dateInput("rec_date", label="Start Date", value = NULL, min = NULL, max = NULL,
              format = "yyyy-mm-dd", startview = "month", weekstart = 0,language = "en", 
              width = NULL, autoclose = TRUE, datesdisabled = NULL, daysofweekdisabled = NULL),
  
    textInput("rec_time", "Start Time (xx:xx or xx:xx:xx)", value = init.time, width = NULL, placeholder = NULL),
    
    numericInput("srate","Sampling Frequency",value=250,min=1,max=1000),
    
    fileInput("static_data", "Upload Data (EDF/CSV/BIN):", multiple = F, accept = c(".csv",".edf",".BIN"),
      width = NULL, buttonLabel = "Browse...",
      placeholder = "No file selected"),
    ##################################### IS THIS THE BEST UI DISPLAY?
    switchInput(inputId = "rec_btn",label = "Bluetoot device name", labelWidth = "80px"),
    ##################################### POSSIBLY SCALE INPUT HERE
    renderTable(head(ExG$ts)),size="l"
  )
)
})
}
```

```{r,file_observer}

## Include Export and Import Options, funcitons is faulty
## DATA upload actions, currently only EDF and csv
if(shiny_running()){
  observeEvent(input$static_data,{
    print("LOADING DATA")
    if(any(grepl(".csv",input$static_data))){
      tmp=fread(input$static_data$datapath)
    }
    if(any(grepl(".BIN",input$static_data))){
      py$import_explorepy(nput$static_data$datapath)
    }
    ExG$srate=as.numeric(input$srate)
    ExG$posix=as.POSIXct(paste(input$rec_date,input$rec_time))
    if(any(grepl(".edf",input$static_data))){
      tmp=import_raw(input$static_data$datapath)
      ExG$srate=tmp[["srate"]]
      tmp=tmp[["signals"]]
    }
    ExG$ts=as.xts(data.frame(tmp),
                seq(ExG$posix,
                    by=1/ExG$srate, length=nrow(data.frame(tmp))))
      # get column names
      graph_data$nodes=update_nodes(base.nodes,tmp)
      biosigs=subset(graph_data$nodes,group=="biological")
      physigs=subset(graph_data$nodes,group=="physical")
      digsigs=subset(graph_data$nodes,group=="digital")

      graph_data$edges=setNames(data.frame(matrix(ncol = 3, nrow = 0)), c("from", "to","id"))
      ExG$freq=ExG$ts
      colnames(ExG$freq)=paste0("Filtered",colnames(ExG$ts))
      ExG$orig.chan=downsample(ExG$freq,60*15)
      ExG$orig.ssa=downsample(ExG$freq,60*15)
      ExG$orig.disp=downsample(ExG$freq,60*15)
      ExG$disp=downsample(ExG$freq,60*15)
      ExG$sight="time"
      ExG$newfile=T
      #
      # ExG$orig.disp=tmp
      # ## reset UI elements below
      # ExG$sight="bird"
       a=first(index(ExG$orig.disp))
       b=last(index(ExG$orig.disp))
      # tmp=downsample(window(ExG$orig.disp,start=a,end=b),250*60)
       ExG$resol=c(a,b)
      # ExG$disp=tmp
      # ExG$newfile=T
    ExG$stages=data.frame("Sleep State (A, W, S1, S2, S3, REM)"="W",
                        "Time (xx:xx or xx:xx:xx)"=first(seq(ExG$posix,by=1/ExG$srate,length=nrow(ExG$ts))),
                        stringsAsFactors = F)
    graph_data$EEG=findexg(graph_data$nodes,graph_data$edges,1)
    graph_data$ECG=findexg(graph_data$nodes,graph_data$edges,2)
    graph_data$EOG=findexg(graph_data$nodes,graph_data$edges,3)
    graph_data$EMG=findexg(graph_data$nodes,graph_data$edges,4)
    print("READIN WORKED")
  })

observeEvent(c(input$srate,input$rec_time,input$rec_date),{
  ExG$srate=input$srate
  ExG$posix=as.POSIXct(paste(input$rec_date,input$rec_time))
})
}

if(shiny_running()){
observeEvent(input$upload,{
  showModal(modalDialog(
    dateInput("rec_date", label="Start Date", value = NULL, min = NULL, max = NULL,
  format = "yyyy-mm-dd", startview = "month", weekstart = 0,
  language = "en", width = NULL, autoclose = TRUE,
  datesdisabled = NULL, daysofweekdisabled = NULL),
  textInput("rec_time", "Start Time (xx:xx or xx:xx:xx)", value = init.time, width = NULL,
  placeholder = NULL),
  numericInput("srate","Sampling Frequency",value=250,min=1,max=1000),
  fileInput("static_data", "Upload Data (EDF/CSV/BIN):", multiple = F, accept = c(".csv",".edf",".BIN"),
      width = NULL, buttonLabel = "Browse...",
      placeholder = "No file selected"),
  switchInput(inputId = "rec_btn",label = "Bluetoot device name", labelWidth = "80px"),
  renderTable(head(ExG$ts)),size="l"
  )
)
})
}

if(shiny_running()){
  observeEvent(input$rec_btn,{
    ########### COMING SOON - REAL SCRIPT #########
    if(input$rec_btn==T){ ### WHILE RECORDING
      plan(multisession)
      # reticulate::source_python(paste0("C:/Users/royde/Desktop/explore_connect.py")) ### CONNECT TO DEVICE AND
      w %<-% { ### EVALUATE PARALLEL
        .libPaths("C:/Users/royde/Documents/R/win-library/4.0") ### GRAB DEFAULTS
        library(reticulate) ### LOAD EM
        mainDir<<-getwd()
        source_python(paste0(mainDir,"/EEG.py")) ### CREATE LSL STREAM  
        py$connect_explore()
      }
      print("GRABBIN DATA")
       ### EVALUATE PARALLEL
        .libPaths("C:/Users/royde/Documents/R/win-library/4.0") ### GRAB DEFAULTS
        library(reticulate) ### LOAD EM
        mainDir<<-getwd()
        source_python(paste0(mainDir,"/EEG.py")) ### CREATE LSL STREAM  
        tmp=c()
        for(i in 1:30){ ### Grab 30 secs (1 Window Length) of data
          tmp=rbind(tmp,data.frame(py$explore_df()))
        }
      tmp=tmp/(1000*1000)
      print("FINISHED GRABBIN")
      ### ALL 5 SECONDS GRAB DATA AND THROW ON GRAPH UNTIL BROKEN
      ### POSSIBLY FIX BY EXG$hold  ??
# init.channels<<-colnames(tmp)
    ExG$ts=as.xts(data.frame(tmp),
                seq(ExG$posix,
                    by=1/ExG$srate, length=nrow(data.frame(tmp))))
    ExG$srate=as.numeric(input$srate)
    ExG$posix=as.POSIXct(paste(input$rec_date,input$rec_time))
      # get column names
      graph_data$nodes=update_nodes(base.nodes,tmp)
      biosigs=subset(graph_data$nodes,group=="biological")
      physigs=subset(graph_data$nodes,group=="physical")
      digsigs=subset(graph_data$nodes,group=="digital")
      #

      graph_data$edges=setNames(data.frame(matrix(ncol = 3, nrow = 0)), c("from", "to","id"))
      ExG$freq=ExG$ts
      colnames(ExG$freq)=paste0("Filtered",colnames(ExG$ts))
      ExG$orig.chan=downsample(ExG$freq,60*15)
      ExG$orig.ssa=downsample(ExG$freq,60*15)
      ExG$orig.disp=downsample(ExG$freq,60*15)
      ExG$disp=downsample(ExG$freq,60*15)
      ExG$newfile=T
      #
      # ExG$orig.disp=tmp
      # ## reset UI elements below
      # ExG$sight="bird"
       a=first(index(ExG$orig.disp))
       b=last(index(ExG$orig.disp))
      # tmp=downsample(window(ExG$orig.disp,start=a,end=b),250*60)
       ExG$resol=c(a,b)
      # ExG$disp=tmp
      # ExG$newfile=T
    ExG$stages=data.frame("Sleep State (A, W, S1, S2, S3, REM)"="W",
                        "Time (xx:xx or xx:xx:xx)"=first(seq(ExG$posix,by=1/ExG$srate,length=nrow(ExG$ts))),
                        stringsAsFactors = F)
    graph_data$EEG=findexg(graph_data$nodes,graph_data$edges,1)
    graph_data$ECG=findexg(graph_data$nodes,graph_data$edges,2)
    graph_data$EOG=findexg(graph_data$nodes,graph_data$edges,3)
    graph_data$EMG=findexg(graph_data$nodes,graph_data$edges,4)
    ExG$recording=T
    print("finished first record")

    }else{
      ExG$recording=F
    }
  })

  observe({
    invalidateLater(45000) ### autoinvalidate after setting values?
    print("updating")
    if(ExG$recording==T){
       ExG_live<-future_promise({ ### EVALUATE PARALLEL
        .libPaths("C:/Users/royde/Documents/R/win-library/4.0") ### GRAB DEFAULTS
        library(reticulate)
        mainDir<<-getwd()
        source_python(paste0(mainDir,"/EEG.py"))
        tmp=c()
        for(i in 1:30){ ### FOR EACH 5 seconds GRAB DATA
          tmp=rbind(tmp,data.frame(py$explore_df()))
        }
        tmp/(1000*1000)
       })
    print("started promise")
    
    then(ExG_live,onFulfilled = function(value) {
      ExG$ts<<-rbind(ExG$ts,as.xts(data.frame(value),
                seq(last(index(ExG$ts))+1,
                    by=1/ExG$srate, length=nrow(data.frame(value)))))
      ExG$freq<<-ExG$ts
      colnames(ExG$freq)=paste0("Filtered",colnames(ExG$ts))
      ExG$orig.chan<<-downsample(ExG$freq,60*15)
      ExG$orig.ssa<<-downsample(ExG$freq,60*15)
      ExG$orig.disp<<-downsample(ExG$freq,60*15)
      ExG$disp<<-downsample(ExG$freq,60*15)
      a=first(index(ExG$orig.disp))
      b=last(index(ExG$orig.disp))
      # tmp=downsample(window(ExG$orig.disp,start=a,end=b),250*60)
      ExG$resol<<-c(a,b)
      ExG$newfile<<-T
  })
    print("evaluated promise")  
    }
  })
}

```

```{r dygraph_staging}
############################## BY CLICK IN DYGRAPH ON STAGES SELECTED -> INPUT NEW STAGE AT CLICK POS
if(shiny_running()){
observeEvent(input[["dygraph_click"]],{
  ########## GET DATE AT POSITION CLICK
  if("Stages" %in% input$disp_event){
  date_click=strsplit(input[["dygraph_click"]][["x"]],"T")[[1]][1]
  ########## GET TIME AT CLICK
  time_click=strsplit(strsplit(input[["dygraph_click"]][["x"]],"T")[[1]][2],"Z")[[1]][1]
  ########## ADJUST TIME FORMAT
  date_time_click=as.POSIXct(paste(date_click,time_click,format="%Y-%m-%d %H:%M:%OS"))+60*60
  ########## ADD TO STAGE DISPLAY
  ExG$stages=
    data.frame(rbind(ExG$stages,
          setNames(data.frame("A",
                              date_time_click,
                              stringsAsFactors = F),
                   colnames(ExG$stages))))
  }
})
############################## BY (DOUBLE-)CLICK ON A STAGE -> CHANGE/DELETE STAGING
observeEvent(input$downRater,{
  if(input$downRater!=0){
  downList=c("A","W","REM","S1","S2","S3")
  if(any(ExG$stages[as.numeric(input$downRater),1] %in% downList)){
     if(ExG$stages[as.numeric(input$downRater),1]!="S3"){
       ExG$stages[as.numeric(input$downRater),1]=
         downList[which(downList %in% ExG$stages[as.numeric(input$downRater),1] )+1]
     }else{
       ExG$stages=ExG$stages[-as.numeric(input$downRater),]
     }}}
})
observeEvent(input$upRater,{
  if(input$upRater!=0){
  upList=c("S3","S2","S1","REM","W","A")
  if(any(ExG$stages[as.numeric(input$upRater),1] %in% upList)){
    if(ExG$stages[as.numeric(input$upRater),1]!="A"){
      ExG$stages[as.numeric(input$upRater),1]=
        upList[which(upList %in% ExG$stages[as.numeric(input$upRater),1] )+1]
    }else{
      ExG$stages=ExG$stages[-as.numeric(input$upRater),]
    }}}
})
}
```

```{r}
## interactive update window
if(shiny_running()){
observeEvent({c(input[["dygraph_date_window"]],
                input$disp_chan,
               input$disp_event,
               input$disp_ssa)},
  {
    if(!ExG$newfile){
  ##Check current display ranges range,timezone conversion etc.
  r1=as.POSIXct(paste(as.character(strsplit(input[["dygraph_date_window"]],"T")[[1]]),collapse = " "),tz="UTC")
  attr(r1,"tzone")<-attributes(ExG$posix)$tzone
  r2=as.POSIXct(paste(as.character(strsplit(input[["dygraph_date_window"]],"T")[[2]]),collapse = " "),tz="UTC")
  attr(r2,"tzone")<-attributes(ExG$posix)$tzone
  range=c(r1,r2)
  d_range=difftime(range[2],range[1],units="secs")
  resize=F
  redat=F
  ## Resolution changed? "bird" -hour, "time"-minute, "detail" -second
  ## if so data need to be resampled resize=T
  if(d_range<60 & ExG$sight!="detail"){
    resize=T
    ExG$sight="detail"
  }
  if((d_range>=60 ) & ExG$sight!="time"){
    resize=T
    ExG$sight="time"
  }
  # if((d_range>=60*30 & d_range<60*60*24) & ExG$sight!="bird"){
  #   resize=T
  #   ExG$sight="bird"
  # }

  ## Select Channels to display - mutually exclusive for Source and Channel
  if(!is.null(input$disp_chan)){
    ## Check for mutually exclusive groups - not working
    if(!all(paste0("Filtered",input$disp_chan) %in% colnames(ExG$orig.chan))|
       !all(colnames(ExG$orig.chan) %in% paste0("Filtered",input$disp_chan))){newdata=T}else{newdata=F}
  }else{
    if(!is.null(colnames(ExG$orig.chan))){newdata=T}else{newdata=F}#####??? WHAT???
  }

  #if anything is not displayed already
  print("NEWDATA")
  if(newdata){
    redat=T
    tmp=xts(rep(NA,length(index(ExG$freq))),index(ExG$freq))
    colnames(tmp)="Empty"
    if(!is.null(input$disp_chan)){
      for(i in 1:length(input$disp_chan)){
        tmp=merge(tmp,ExG$freq[,paste0("Filtered",input$disp_chan[i])])
      }
      ExG$orig.chan=tmp[,colSums(is.na(tmp))<1000] ### CHEESY -> NOT COLSUMS?? -> BUG?
    }else{
      ExG$orig.chan=tmp
    }
    # ExG$colors=c("#ffffe5","#f7fcb9","#d9f0a3","#addd8e","#78c679","#41ab5d","#238443","#005a32")[
    #   colnames(ExG$freq) %in% sort(paste0("Filtered",input$disp_chan))
    # ]
  }
  print("NEWCLUSTER")
  newclust=(!all(input$disp_ssa %in% colnames(ExG$orig.ssa)))|
    (!all(colnames(ExG$orig.ssa) %in% input$disp_ssa))
  if(redat|newclust){
    redat=T
    tmp=ExG$orig.chan
    # if(input$clust_disp){
      # ExG$rssa<-recons(ExG$ssa,ExG$gssa,stacked = F)
    # }else{
    #   ExG$rssa<-recons(ExG$ssa,ExG$gssa,separate = T)
    #}
    for(i in input$disp_ssa){
      tmp=merge(tmp, ExG$rssa[,i])
    }
    ExG$orig.ssa=tmp
  }

  ## Check if alpha band is already displayed, not clean
  test_q1=(!any(grepl("Alp",colnames(ExG$orig.disp))) & "Bandpower" %in% input[["disp_event"]])|
      (any(grepl("Alp",colnames(ExG$orig.disp))) & !("Bandpower" %in% input[["disp_event"]]))

  # Check not implemented
  # test_q2=(all(graph_data$EEG %in% colnames(ExG$orig.disp)) & !("Raw Signal" %in% input$disp_event))|
  #               (!all(graph_data$EEG %in% colnames(ExG$orig.disp)) & ( "Raw Signal" %in% input$disp_event))

  if(test_q1|redat){
    # if(input$clust_disp){}
    redat=T
    tmp=ExG$orig.ssa
    # if("Raw Signal" %in% input$disp_event){
    #   tmp=merge(tmp,ExG$ts[,unlist(lapply(strsplit(colnames(ExG$orig.chan),"Filtered"),function(x)x[[2]]))])   }
  if("Bandpower" %in% input$disp_event){tmp=merge(tmp,ExG$bandpower)}
    ExG$orig.disp=tmp
    print(head(ExG$orig.disp))
  }

  # Update Resolution of data
  if(range[2]>min(last(index(ExG$orig.disp)),ExG$resol[2])||
     range[1]<max(first(index(ExG$orig.disp)),ExG$resol[1])||
     resize||redat){
    ## if new data selection, dont change resolution borders
    if(!redat){
      r1=max(first(index(ExG$orig.disp)),range[1]-10*d_range)
      r2=min(last(index(ExG$orig.disp)),range[2]+10*d_range)
    }else{
      print(range[1])
      r1=range[1]
      r2=range[2]
    }
    redat=F
      #Seconds down to full
    if(ExG$sight=="detail"){
      if(r1!=first(index(ExG$orig.disp))){
        ## downsample out of scope to minutes, rest complete
        print(ExG$posix)
          print(first(index(ExG$orig.disp)))
          print(r1)
                    print(length(ExG$ts))
          print(length(ExG$disp))
          tmp=rbind(
            downsample(window(ExG$orig.disp,start=first(index(ExG$orig.disp)),end=r1),60*ExG$srate*5),
            window(ExG$orig.disp,start=r1,end=r2))
      }else tmp=window(ExG$orig.disp,start=r1,end=r2)
      if(r2!=last(index(ExG$orig.disp))){
          tmp=rbind(tmp,
          downsample(window(ExG$orig.disp,start=r2,end=last(index(ExG$orig.disp))),ExG$srate*60*5))}
      }
        # Minutes , down to seconds
    if(ExG$sight=="time"){
        if(r1!=first(index(ExG$orig.disp))){
          ## downsample out of scope to minutes, rest to seconds
          print(ExG$posix)
          print(first(index(ExG$orig.disp)))
          print(r1)
          print(length(ExG$ts))
          print(length(ExG$disp))
          tmp=rbind(
              downsample(window(ExG$orig.disp,start=first(index(ExG$orig.disp)),end=r1),ExG$srate),
              downsample(window(ExG$orig.disp,start=r1,end=r2),ExG$srate))
          }else{ tmp=downsample(window(ExG$orig.disp,start=r1,end=r2),ExG$srate)}
          if(r2!=last(index(ExG$orig.disp))){
            tmp=rbind(tmp,
            downsample(window(ExG$orig.disp,start=r2,end=last(index(ExG$orig.disp))),ExG$srate))}
    }
  #hours down to minutes
  # if(ExG$sight=="bird"){
  #   if(a!=first(index(ExG$orig.disp))){
  #       tmp=rbind(
  #         downsample(window(ExG$orig.disp,start=first(index(ExG$orig.disp)),end=a),250*60*10),
  #         downsample(window(ExG$orig.disp,start=a,end=b),250*60))
  #       }else{
  #           tmp=downsample(window(ExG$orig.disp,start=a,end=b),250*60)
  #         }
  #     if(b!=last(index(ExG$orig.disp))){
  #       tmp=rbind(tmp,
  #       downsample(window(ExG$orig.disp,start=b,end=last(index(ExG$orig.disp))),250*60*10))
  #       }
  # }
      ExG$resol=c(r1,r2)
      ExG$disp=tmp
  }
    }else{
      Sys.sleep(5)
       ExG$newfile=F
     }
})
}
```